### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [nikita-shpikin/myFirstSlider#1]
1. https://github.com/nikita-shpikin/myFirstSlider/blob/64eb4de6a59fe3db0fc98a578d6c5fc13fd61f07/js/main.js#L43 Чтобы заработало - вам просто нужно добавить функционал УДАЛЕНИЯ стилей перед присвоением. Пробегаетесь по всем элементам `menu` и делаете `classList.remove("projects-menu__link--gold")`. То же самое для точек
2. https://github.com/nikita-shpikin/myFirstSlider/blob/64eb4de6a59fe3db0fc98a578d6c5fc13fd61f07/js/main.js#L112 А если мы добавим еще 10 сладйов? Насколько вырастет ваш код? Нужно убирать условия и отталкиваться от передаваемого индекса
3. `setTimeout` везде лишний

**Comment by nikita-shpikin** [comment]
Всё исправил отправляю на проверку :)
